# Railway Configuration for Backend Deployment
[build]
  command = "cd server && npm install"

[deploy]
  startCommand = "cd server && npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

# Environment variables will be set in Railway dashboard
[variables]
