# Railway Configuration for Backend Deployment
[build]
  command = "cd server && npm install"

[deploy]
  startCommand = "cd server && npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 30
  restartPolicyType = "on_failure"

# Ensure variables are available
[variables]
